// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackendData.proto

package com.noname.backend;

public final class BackendPayload {
  private BackendPayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Payload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Payload.Request simpleRequest = 1;</code>
     */
    boolean hasSimpleRequest();
    /**
     * <code>optional .Payload.Request simpleRequest = 1;</code>
     */
    com.noname.backend.BackendPayload.Payload.Request getSimpleRequest();
    /**
     * <code>optional .Payload.Request simpleRequest = 1;</code>
     */
    com.noname.backend.BackendPayload.Payload.RequestOrBuilder getSimpleRequestOrBuilder();

    /**
     * <code>optional .Payload.Response simpleResponse = 2;</code>
     */
    boolean hasSimpleResponse();
    /**
     * <code>optional .Payload.Response simpleResponse = 2;</code>
     */
    com.noname.backend.BackendPayload.Payload.Response getSimpleResponse();
    /**
     * <code>optional .Payload.Response simpleResponse = 2;</code>
     */
    com.noname.backend.BackendPayload.Payload.ResponseOrBuilder getSimpleResponseOrBuilder();
  }
  /**
   * Protobuf type {@code Payload}
   */
  public  static final class Payload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Payload)
      PayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Payload.newBuilder() to construct.
    private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Payload() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.noname.backend.BackendPayload.Payload.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = simpleRequest_.toBuilder();
              }
              simpleRequest_ = input.readMessage(com.noname.backend.BackendPayload.Payload.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simpleRequest_);
                simpleRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.noname.backend.BackendPayload.Payload.Response.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = simpleResponse_.toBuilder();
              }
              simpleResponse_ = input.readMessage(com.noname.backend.BackendPayload.Payload.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simpleResponse_);
                simpleResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.noname.backend.BackendPayload.internal_static_Payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.noname.backend.BackendPayload.internal_static_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.noname.backend.BackendPayload.Payload.class, com.noname.backend.BackendPayload.Payload.Builder.class);
    }

    public interface RequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Payload.Request)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 requestCode = 1;</code>
       */
      boolean hasRequestCode();
      /**
       * <code>required int32 requestCode = 1;</code>
       */
      int getRequestCode();

      /**
       * <code>required string content = 2;</code>
       */
      boolean hasContent();
      /**
       * <code>required string content = 2;</code>
       */
      java.lang.String getContent();
      /**
       * <code>required string content = 2;</code>
       */
      com.google.protobuf.ByteString
          getContentBytes();
    }
    /**
     * Protobuf type {@code Payload.Request}
     */
    public  static final class Request extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Payload.Request)
        RequestOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Request.newBuilder() to construct.
      private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Request() {
        requestCode_ = 0;
        content_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Request(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                requestCode_ = input.readInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                content_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.noname.backend.BackendPayload.internal_static_Payload_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.noname.backend.BackendPayload.internal_static_Payload_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.noname.backend.BackendPayload.Payload.Request.class, com.noname.backend.BackendPayload.Payload.Request.Builder.class);
      }

      private int bitField0_;
      public static final int REQUESTCODE_FIELD_NUMBER = 1;
      private int requestCode_;
      /**
       * <code>required int32 requestCode = 1;</code>
       */
      public boolean hasRequestCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 requestCode = 1;</code>
       */
      public int getRequestCode() {
        return requestCode_;
      }

      public static final int CONTENT_FIELD_NUMBER = 2;
      private volatile java.lang.Object content_;
      /**
       * <code>required string content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasRequestCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasContent()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, requestCode_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, requestCode_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.noname.backend.BackendPayload.Payload.Request)) {
          return super.equals(obj);
        }
        com.noname.backend.BackendPayload.Payload.Request other = (com.noname.backend.BackendPayload.Payload.Request) obj;

        boolean result = true;
        result = result && (hasRequestCode() == other.hasRequestCode());
        if (hasRequestCode()) {
          result = result && (getRequestCode()
              == other.getRequestCode());
        }
        result = result && (hasContent() == other.hasContent());
        if (hasContent()) {
          result = result && getContent()
              .equals(other.getContent());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasRequestCode()) {
          hash = (37 * hash) + REQUESTCODE_FIELD_NUMBER;
          hash = (53 * hash) + getRequestCode();
        }
        if (hasContent()) {
          hash = (37 * hash) + CONTENT_FIELD_NUMBER;
          hash = (53 * hash) + getContent().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.noname.backend.BackendPayload.Payload.Request parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.noname.backend.BackendPayload.Payload.Request prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Payload.Request}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Payload.Request)
          com.noname.backend.BackendPayload.Payload.RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.noname.backend.BackendPayload.internal_static_Payload_Request_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.noname.backend.BackendPayload.internal_static_Payload_Request_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.noname.backend.BackendPayload.Payload.Request.class, com.noname.backend.BackendPayload.Payload.Request.Builder.class);
        }

        // Construct using com.noname.backend.BackendPayload.Payload.Request.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          requestCode_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          content_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.noname.backend.BackendPayload.internal_static_Payload_Request_descriptor;
        }

        @java.lang.Override
        public com.noname.backend.BackendPayload.Payload.Request getDefaultInstanceForType() {
          return com.noname.backend.BackendPayload.Payload.Request.getDefaultInstance();
        }

        @java.lang.Override
        public com.noname.backend.BackendPayload.Payload.Request build() {
          com.noname.backend.BackendPayload.Payload.Request result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.noname.backend.BackendPayload.Payload.Request buildPartial() {
          com.noname.backend.BackendPayload.Payload.Request result = new com.noname.backend.BackendPayload.Payload.Request(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.requestCode_ = requestCode_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.content_ = content_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.noname.backend.BackendPayload.Payload.Request) {
            return mergeFrom((com.noname.backend.BackendPayload.Payload.Request)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.noname.backend.BackendPayload.Payload.Request other) {
          if (other == com.noname.backend.BackendPayload.Payload.Request.getDefaultInstance()) return this;
          if (other.hasRequestCode()) {
            setRequestCode(other.getRequestCode());
          }
          if (other.hasContent()) {
            bitField0_ |= 0x00000002;
            content_ = other.content_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasRequestCode()) {
            return false;
          }
          if (!hasContent()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.noname.backend.BackendPayload.Payload.Request parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.noname.backend.BackendPayload.Payload.Request) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int requestCode_ ;
        /**
         * <code>required int32 requestCode = 1;</code>
         */
        public boolean hasRequestCode() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 requestCode = 1;</code>
         */
        public int getRequestCode() {
          return requestCode_;
        }
        /**
         * <code>required int32 requestCode = 1;</code>
         */
        public Builder setRequestCode(int value) {
          bitField0_ |= 0x00000001;
          requestCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 requestCode = 1;</code>
         */
        public Builder clearRequestCode() {
          bitField0_ = (bitField0_ & ~0x00000001);
          requestCode_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object content_ = "";
        /**
         * <code>required string content = 2;</code>
         */
        public boolean hasContent() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string content = 2;</code>
         */
        public java.lang.String getContent() {
          java.lang.Object ref = content_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              content_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string content = 2;</code>
         */
        public com.google.protobuf.ByteString
            getContentBytes() {
          java.lang.Object ref = content_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            content_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string content = 2;</code>
         */
        public Builder setContent(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          content_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string content = 2;</code>
         */
        public Builder clearContent() {
          bitField0_ = (bitField0_ & ~0x00000002);
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        /**
         * <code>required string content = 2;</code>
         */
        public Builder setContentBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          content_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Payload.Request)
      }

      // @@protoc_insertion_point(class_scope:Payload.Request)
      private static final com.noname.backend.BackendPayload.Payload.Request DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.noname.backend.BackendPayload.Payload.Request();
      }

      public static com.noname.backend.BackendPayload.Payload.Request getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
          PARSER = new com.google.protobuf.AbstractParser<Request>() {
        @java.lang.Override
        public Request parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Request> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.noname.backend.BackendPayload.Payload.Request getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface ResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Payload.Response)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 result = 1;</code>
       */
      boolean hasResult();
      /**
       * <code>required int32 result = 1;</code>
       */
      int getResult();

      /**
       * <code>required int32 requestCode = 2;</code>
       */
      boolean hasRequestCode();
      /**
       * <code>required int32 requestCode = 2;</code>
       */
      int getRequestCode();

      /**
       * <code>required string content = 3;</code>
       */
      boolean hasContent();
      /**
       * <code>required string content = 3;</code>
       */
      java.lang.String getContent();
      /**
       * <code>required string content = 3;</code>
       */
      com.google.protobuf.ByteString
          getContentBytes();
    }
    /**
     * Protobuf type {@code Payload.Response}
     */
    public  static final class Response extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Payload.Response)
        ResponseOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Response.newBuilder() to construct.
      private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Response() {
        result_ = 0;
        requestCode_ = 0;
        content_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Response(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                result_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                requestCode_ = input.readInt32();
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                content_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.noname.backend.BackendPayload.internal_static_Payload_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.noname.backend.BackendPayload.internal_static_Payload_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.noname.backend.BackendPayload.Payload.Response.class, com.noname.backend.BackendPayload.Payload.Response.Builder.class);
      }

      private int bitField0_;
      public static final int RESULT_FIELD_NUMBER = 1;
      private int result_;
      /**
       * <code>required int32 result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }

      public static final int REQUESTCODE_FIELD_NUMBER = 2;
      private int requestCode_;
      /**
       * <code>required int32 requestCode = 2;</code>
       */
      public boolean hasRequestCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 requestCode = 2;</code>
       */
      public int getRequestCode() {
        return requestCode_;
      }

      public static final int CONTENT_FIELD_NUMBER = 3;
      private volatile java.lang.Object content_;
      /**
       * <code>required string content = 3;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasResult()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasRequestCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasContent()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, result_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, requestCode_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, result_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, requestCode_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.noname.backend.BackendPayload.Payload.Response)) {
          return super.equals(obj);
        }
        com.noname.backend.BackendPayload.Payload.Response other = (com.noname.backend.BackendPayload.Payload.Response) obj;

        boolean result = true;
        result = result && (hasResult() == other.hasResult());
        if (hasResult()) {
          result = result && (getResult()
              == other.getResult());
        }
        result = result && (hasRequestCode() == other.hasRequestCode());
        if (hasRequestCode()) {
          result = result && (getRequestCode()
              == other.getRequestCode());
        }
        result = result && (hasContent() == other.hasContent());
        if (hasContent()) {
          result = result && getContent()
              .equals(other.getContent());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasResult()) {
          hash = (37 * hash) + RESULT_FIELD_NUMBER;
          hash = (53 * hash) + getResult();
        }
        if (hasRequestCode()) {
          hash = (37 * hash) + REQUESTCODE_FIELD_NUMBER;
          hash = (53 * hash) + getRequestCode();
        }
        if (hasContent()) {
          hash = (37 * hash) + CONTENT_FIELD_NUMBER;
          hash = (53 * hash) + getContent().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.noname.backend.BackendPayload.Payload.Response parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.noname.backend.BackendPayload.Payload.Response prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Payload.Response}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Payload.Response)
          com.noname.backend.BackendPayload.Payload.ResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.noname.backend.BackendPayload.internal_static_Payload_Response_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.noname.backend.BackendPayload.internal_static_Payload_Response_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.noname.backend.BackendPayload.Payload.Response.class, com.noname.backend.BackendPayload.Payload.Response.Builder.class);
        }

        // Construct using com.noname.backend.BackendPayload.Payload.Response.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          result_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          requestCode_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          content_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.noname.backend.BackendPayload.internal_static_Payload_Response_descriptor;
        }

        @java.lang.Override
        public com.noname.backend.BackendPayload.Payload.Response getDefaultInstanceForType() {
          return com.noname.backend.BackendPayload.Payload.Response.getDefaultInstance();
        }

        @java.lang.Override
        public com.noname.backend.BackendPayload.Payload.Response build() {
          com.noname.backend.BackendPayload.Payload.Response result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.noname.backend.BackendPayload.Payload.Response buildPartial() {
          com.noname.backend.BackendPayload.Payload.Response result = new com.noname.backend.BackendPayload.Payload.Response(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.result_ = result_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.requestCode_ = requestCode_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.content_ = content_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.noname.backend.BackendPayload.Payload.Response) {
            return mergeFrom((com.noname.backend.BackendPayload.Payload.Response)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.noname.backend.BackendPayload.Payload.Response other) {
          if (other == com.noname.backend.BackendPayload.Payload.Response.getDefaultInstance()) return this;
          if (other.hasResult()) {
            setResult(other.getResult());
          }
          if (other.hasRequestCode()) {
            setRequestCode(other.getRequestCode());
          }
          if (other.hasContent()) {
            bitField0_ |= 0x00000004;
            content_ = other.content_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasResult()) {
            return false;
          }
          if (!hasRequestCode()) {
            return false;
          }
          if (!hasContent()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.noname.backend.BackendPayload.Payload.Response parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.noname.backend.BackendPayload.Payload.Response) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int result_ ;
        /**
         * <code>required int32 result = 1;</code>
         */
        public boolean hasResult() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 result = 1;</code>
         */
        public int getResult() {
          return result_;
        }
        /**
         * <code>required int32 result = 1;</code>
         */
        public Builder setResult(int value) {
          bitField0_ |= 0x00000001;
          result_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 result = 1;</code>
         */
        public Builder clearResult() {
          bitField0_ = (bitField0_ & ~0x00000001);
          result_ = 0;
          onChanged();
          return this;
        }

        private int requestCode_ ;
        /**
         * <code>required int32 requestCode = 2;</code>
         */
        public boolean hasRequestCode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 requestCode = 2;</code>
         */
        public int getRequestCode() {
          return requestCode_;
        }
        /**
         * <code>required int32 requestCode = 2;</code>
         */
        public Builder setRequestCode(int value) {
          bitField0_ |= 0x00000002;
          requestCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 requestCode = 2;</code>
         */
        public Builder clearRequestCode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          requestCode_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object content_ = "";
        /**
         * <code>required string content = 3;</code>
         */
        public boolean hasContent() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string content = 3;</code>
         */
        public java.lang.String getContent() {
          java.lang.Object ref = content_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              content_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string content = 3;</code>
         */
        public com.google.protobuf.ByteString
            getContentBytes() {
          java.lang.Object ref = content_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            content_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string content = 3;</code>
         */
        public Builder setContent(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          content_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string content = 3;</code>
         */
        public Builder clearContent() {
          bitField0_ = (bitField0_ & ~0x00000004);
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        /**
         * <code>required string content = 3;</code>
         */
        public Builder setContentBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          content_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Payload.Response)
      }

      // @@protoc_insertion_point(class_scope:Payload.Response)
      private static final com.noname.backend.BackendPayload.Payload.Response DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.noname.backend.BackendPayload.Payload.Response();
      }

      public static com.noname.backend.BackendPayload.Payload.Response getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
          PARSER = new com.google.protobuf.AbstractParser<Response>() {
        @java.lang.Override
        public Response parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Response> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Response> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.noname.backend.BackendPayload.Payload.Response getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int SIMPLEREQUEST_FIELD_NUMBER = 1;
    private com.noname.backend.BackendPayload.Payload.Request simpleRequest_;
    /**
     * <code>optional .Payload.Request simpleRequest = 1;</code>
     */
    public boolean hasSimpleRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Payload.Request simpleRequest = 1;</code>
     */
    public com.noname.backend.BackendPayload.Payload.Request getSimpleRequest() {
      return simpleRequest_ == null ? com.noname.backend.BackendPayload.Payload.Request.getDefaultInstance() : simpleRequest_;
    }
    /**
     * <code>optional .Payload.Request simpleRequest = 1;</code>
     */
    public com.noname.backend.BackendPayload.Payload.RequestOrBuilder getSimpleRequestOrBuilder() {
      return simpleRequest_ == null ? com.noname.backend.BackendPayload.Payload.Request.getDefaultInstance() : simpleRequest_;
    }

    public static final int SIMPLERESPONSE_FIELD_NUMBER = 2;
    private com.noname.backend.BackendPayload.Payload.Response simpleResponse_;
    /**
     * <code>optional .Payload.Response simpleResponse = 2;</code>
     */
    public boolean hasSimpleResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Payload.Response simpleResponse = 2;</code>
     */
    public com.noname.backend.BackendPayload.Payload.Response getSimpleResponse() {
      return simpleResponse_ == null ? com.noname.backend.BackendPayload.Payload.Response.getDefaultInstance() : simpleResponse_;
    }
    /**
     * <code>optional .Payload.Response simpleResponse = 2;</code>
     */
    public com.noname.backend.BackendPayload.Payload.ResponseOrBuilder getSimpleResponseOrBuilder() {
      return simpleResponse_ == null ? com.noname.backend.BackendPayload.Payload.Response.getDefaultInstance() : simpleResponse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasSimpleRequest()) {
        if (!getSimpleRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSimpleResponse()) {
        if (!getSimpleResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getSimpleRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getSimpleResponse());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSimpleRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSimpleResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.noname.backend.BackendPayload.Payload)) {
        return super.equals(obj);
      }
      com.noname.backend.BackendPayload.Payload other = (com.noname.backend.BackendPayload.Payload) obj;

      boolean result = true;
      result = result && (hasSimpleRequest() == other.hasSimpleRequest());
      if (hasSimpleRequest()) {
        result = result && getSimpleRequest()
            .equals(other.getSimpleRequest());
      }
      result = result && (hasSimpleResponse() == other.hasSimpleResponse());
      if (hasSimpleResponse()) {
        result = result && getSimpleResponse()
            .equals(other.getSimpleResponse());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSimpleRequest()) {
        hash = (37 * hash) + SIMPLEREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getSimpleRequest().hashCode();
      }
      if (hasSimpleResponse()) {
        hash = (37 * hash) + SIMPLERESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getSimpleResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.noname.backend.BackendPayload.Payload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.noname.backend.BackendPayload.Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.noname.backend.BackendPayload.Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.noname.backend.BackendPayload.Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.noname.backend.BackendPayload.Payload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Payload)
        com.noname.backend.BackendPayload.PayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.noname.backend.BackendPayload.internal_static_Payload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.noname.backend.BackendPayload.internal_static_Payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.noname.backend.BackendPayload.Payload.class, com.noname.backend.BackendPayload.Payload.Builder.class);
      }

      // Construct using com.noname.backend.BackendPayload.Payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSimpleRequestFieldBuilder();
          getSimpleResponseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (simpleRequestBuilder_ == null) {
          simpleRequest_ = null;
        } else {
          simpleRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (simpleResponseBuilder_ == null) {
          simpleResponse_ = null;
        } else {
          simpleResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.noname.backend.BackendPayload.internal_static_Payload_descriptor;
      }

      @java.lang.Override
      public com.noname.backend.BackendPayload.Payload getDefaultInstanceForType() {
        return com.noname.backend.BackendPayload.Payload.getDefaultInstance();
      }

      @java.lang.Override
      public com.noname.backend.BackendPayload.Payload build() {
        com.noname.backend.BackendPayload.Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.noname.backend.BackendPayload.Payload buildPartial() {
        com.noname.backend.BackendPayload.Payload result = new com.noname.backend.BackendPayload.Payload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (simpleRequestBuilder_ == null) {
          result.simpleRequest_ = simpleRequest_;
        } else {
          result.simpleRequest_ = simpleRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (simpleResponseBuilder_ == null) {
          result.simpleResponse_ = simpleResponse_;
        } else {
          result.simpleResponse_ = simpleResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.noname.backend.BackendPayload.Payload) {
          return mergeFrom((com.noname.backend.BackendPayload.Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.noname.backend.BackendPayload.Payload other) {
        if (other == com.noname.backend.BackendPayload.Payload.getDefaultInstance()) return this;
        if (other.hasSimpleRequest()) {
          mergeSimpleRequest(other.getSimpleRequest());
        }
        if (other.hasSimpleResponse()) {
          mergeSimpleResponse(other.getSimpleResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasSimpleRequest()) {
          if (!getSimpleRequest().isInitialized()) {
            return false;
          }
        }
        if (hasSimpleResponse()) {
          if (!getSimpleResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.noname.backend.BackendPayload.Payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.noname.backend.BackendPayload.Payload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.noname.backend.BackendPayload.Payload.Request simpleRequest_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.noname.backend.BackendPayload.Payload.Request, com.noname.backend.BackendPayload.Payload.Request.Builder, com.noname.backend.BackendPayload.Payload.RequestOrBuilder> simpleRequestBuilder_;
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public boolean hasSimpleRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public com.noname.backend.BackendPayload.Payload.Request getSimpleRequest() {
        if (simpleRequestBuilder_ == null) {
          return simpleRequest_ == null ? com.noname.backend.BackendPayload.Payload.Request.getDefaultInstance() : simpleRequest_;
        } else {
          return simpleRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public Builder setSimpleRequest(com.noname.backend.BackendPayload.Payload.Request value) {
        if (simpleRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simpleRequest_ = value;
          onChanged();
        } else {
          simpleRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public Builder setSimpleRequest(
          com.noname.backend.BackendPayload.Payload.Request.Builder builderForValue) {
        if (simpleRequestBuilder_ == null) {
          simpleRequest_ = builderForValue.build();
          onChanged();
        } else {
          simpleRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public Builder mergeSimpleRequest(com.noname.backend.BackendPayload.Payload.Request value) {
        if (simpleRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              simpleRequest_ != null &&
              simpleRequest_ != com.noname.backend.BackendPayload.Payload.Request.getDefaultInstance()) {
            simpleRequest_ =
              com.noname.backend.BackendPayload.Payload.Request.newBuilder(simpleRequest_).mergeFrom(value).buildPartial();
          } else {
            simpleRequest_ = value;
          }
          onChanged();
        } else {
          simpleRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public Builder clearSimpleRequest() {
        if (simpleRequestBuilder_ == null) {
          simpleRequest_ = null;
          onChanged();
        } else {
          simpleRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public com.noname.backend.BackendPayload.Payload.Request.Builder getSimpleRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSimpleRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      public com.noname.backend.BackendPayload.Payload.RequestOrBuilder getSimpleRequestOrBuilder() {
        if (simpleRequestBuilder_ != null) {
          return simpleRequestBuilder_.getMessageOrBuilder();
        } else {
          return simpleRequest_ == null ?
              com.noname.backend.BackendPayload.Payload.Request.getDefaultInstance() : simpleRequest_;
        }
      }
      /**
       * <code>optional .Payload.Request simpleRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.noname.backend.BackendPayload.Payload.Request, com.noname.backend.BackendPayload.Payload.Request.Builder, com.noname.backend.BackendPayload.Payload.RequestOrBuilder> 
          getSimpleRequestFieldBuilder() {
        if (simpleRequestBuilder_ == null) {
          simpleRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.noname.backend.BackendPayload.Payload.Request, com.noname.backend.BackendPayload.Payload.Request.Builder, com.noname.backend.BackendPayload.Payload.RequestOrBuilder>(
                  getSimpleRequest(),
                  getParentForChildren(),
                  isClean());
          simpleRequest_ = null;
        }
        return simpleRequestBuilder_;
      }

      private com.noname.backend.BackendPayload.Payload.Response simpleResponse_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.noname.backend.BackendPayload.Payload.Response, com.noname.backend.BackendPayload.Payload.Response.Builder, com.noname.backend.BackendPayload.Payload.ResponseOrBuilder> simpleResponseBuilder_;
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public boolean hasSimpleResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public com.noname.backend.BackendPayload.Payload.Response getSimpleResponse() {
        if (simpleResponseBuilder_ == null) {
          return simpleResponse_ == null ? com.noname.backend.BackendPayload.Payload.Response.getDefaultInstance() : simpleResponse_;
        } else {
          return simpleResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public Builder setSimpleResponse(com.noname.backend.BackendPayload.Payload.Response value) {
        if (simpleResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simpleResponse_ = value;
          onChanged();
        } else {
          simpleResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public Builder setSimpleResponse(
          com.noname.backend.BackendPayload.Payload.Response.Builder builderForValue) {
        if (simpleResponseBuilder_ == null) {
          simpleResponse_ = builderForValue.build();
          onChanged();
        } else {
          simpleResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public Builder mergeSimpleResponse(com.noname.backend.BackendPayload.Payload.Response value) {
        if (simpleResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              simpleResponse_ != null &&
              simpleResponse_ != com.noname.backend.BackendPayload.Payload.Response.getDefaultInstance()) {
            simpleResponse_ =
              com.noname.backend.BackendPayload.Payload.Response.newBuilder(simpleResponse_).mergeFrom(value).buildPartial();
          } else {
            simpleResponse_ = value;
          }
          onChanged();
        } else {
          simpleResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public Builder clearSimpleResponse() {
        if (simpleResponseBuilder_ == null) {
          simpleResponse_ = null;
          onChanged();
        } else {
          simpleResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public com.noname.backend.BackendPayload.Payload.Response.Builder getSimpleResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSimpleResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      public com.noname.backend.BackendPayload.Payload.ResponseOrBuilder getSimpleResponseOrBuilder() {
        if (simpleResponseBuilder_ != null) {
          return simpleResponseBuilder_.getMessageOrBuilder();
        } else {
          return simpleResponse_ == null ?
              com.noname.backend.BackendPayload.Payload.Response.getDefaultInstance() : simpleResponse_;
        }
      }
      /**
       * <code>optional .Payload.Response simpleResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.noname.backend.BackendPayload.Payload.Response, com.noname.backend.BackendPayload.Payload.Response.Builder, com.noname.backend.BackendPayload.Payload.ResponseOrBuilder> 
          getSimpleResponseFieldBuilder() {
        if (simpleResponseBuilder_ == null) {
          simpleResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.noname.backend.BackendPayload.Payload.Response, com.noname.backend.BackendPayload.Payload.Response.Builder, com.noname.backend.BackendPayload.Payload.ResponseOrBuilder>(
                  getSimpleResponse(),
                  getParentForChildren(),
                  isClean());
          simpleResponse_ = null;
        }
        return simpleResponseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Payload)
    }

    // @@protoc_insertion_point(class_scope:Payload)
    private static final com.noname.backend.BackendPayload.Payload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.noname.backend.BackendPayload.Payload();
    }

    public static com.noname.backend.BackendPayload.Payload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Payload>
        PARSER = new com.google.protobuf.AbstractParser<Payload>() {
      @java.lang.Override
      public Payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Payload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Payload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.noname.backend.BackendPayload.Payload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payload_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BackendData.proto\"\320\001\n\007Payload\022\'\n\rsimpl" +
      "eRequest\030\001 \001(\0132\020.Payload.Request\022)\n\016simp" +
      "leResponse\030\002 \001(\0132\021.Payload.Response\032/\n\007R" +
      "equest\022\023\n\013requestCode\030\001 \002(\005\022\017\n\007content\030\002" +
      " \002(\t\032@\n\010Response\022\016\n\006result\030\001 \002(\005\022\023\n\013requ" +
      "estCode\030\002 \002(\005\022\017\n\007content\030\003 \002(\tB$\n\022com.no" +
      "name.backendB\016BackendPayload"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new java.lang.String[] { "SimpleRequest", "SimpleResponse", });
    internal_static_Payload_Request_descriptor =
      internal_static_Payload_descriptor.getNestedTypes().get(0);
    internal_static_Payload_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_Request_descriptor,
        new java.lang.String[] { "RequestCode", "Content", });
    internal_static_Payload_Response_descriptor =
      internal_static_Payload_descriptor.getNestedTypes().get(1);
    internal_static_Payload_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payload_Response_descriptor,
        new java.lang.String[] { "Result", "RequestCode", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
